#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Coding assignment 1"""


def listDivide(numbers, divide=2):
	"""This function retruns the number of elements in the numbers list that are divisible by divide"""
	dcount = 0
	for item in numbers:
		if item % divide is 0:
				dcount += 1
	return dcount
	
class ListDivideException(Exception):
		"""testListDivide will prompt Exception if not divisible"""
		pass

		
def testListDivide():
	"""This function tests listDivide above"""
	if listDivide([1, 2, 3, 4, 5]) !=2
		raise ListDivideException
	elif listDivide([2, 4, 6, 8, 10]) != 5:
		raise ListDivideException
	elif listDivide([30, 54, 63, 98, 100], 10) !=2:
		raise ListDivideException
	elif listDivide([]) != 0:
		raise ListDivideException
	elif listDivide([1, 2, 3, 4, 5], 1) != 5:
		raise ListDivideException
