#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Coding assignment 1, P2"""


class Book(object):
  author = " "
  title = " "
  
  def __init__(self, author, title):
    self.author = author
    self.title = title
  
  def display(self):
    bookinfo = '"{}, written by {}"'.format(self.title, self.author)
    print bookinfo
    
BOOK_1 = Book('John Steinbeck', 'Of Mice and Men')
BOOK_2 = Book('Harper Lee', 'To Kill a Mockingbird')

BOOK_1.display()
BOOK_2.display()
